// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PxOperations.Infrastructure.Persistence;

#nullable disable

namespace PxOperations.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PxOperations.Domain.Milestones.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Email");

                    b.ToTable("nps_contacts", (string)null);
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.Dispatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId", "Format")
                        .IsUnique()
                        .HasFilter("status = 0");

                    b.ToTable("nps_dispatches", (string)null);
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.DispatchTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("integer")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DispatchId")
                        .HasColumnType("integer")
                        .HasColumnName("dispatch_id");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("DispatchId", "ContactId")
                        .IsUnique()
                        .HasFilter("contact_id IS NOT NULL");

                    b.ToTable("nps_dispatch_targets", (string)null);
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.NpsCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("WaivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waived_at");

                    b.Property<string>("WaiverReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("waiver_reason");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("nps_collections", (string)null);
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessValue")
                        .HasColumnType("integer")
                        .HasColumnName("business_value");

                    b.Property<int>("Classification")
                        .HasColumnType("integer")
                        .HasColumnName("classification");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<int?>("Communication")
                        .HasColumnType("integer")
                        .HasColumnName("communication");

                    b.Property<int?>("ContactId")
                        .HasColumnType("integer")
                        .HasColumnName("contact_id");

                    b.Property<int>("DispatchId")
                        .HasColumnType("integer")
                        .HasColumnName("dispatch_id");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("NormalizedRespondentEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_respondent_email");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int?>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<string>("RespondentEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("respondent_email");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("respondent_name");

                    b.Property<int?>("Schedule")
                        .HasColumnType("integer")
                        .HasColumnName("schedule");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("TargetId")
                        .IsUnique()
                        .HasFilter("contact_id IS NOT NULL");

                    b.HasIndex("DispatchId", "SubmittedAt");

                    b.HasIndex("ProjectId", "SubmittedAt");

                    b.HasIndex("TargetId", "NormalizedRespondentEmail")
                        .IsUnique()
                        .HasFilter("contact_id IS NULL AND normalized_respondent_email IS NOT NULL");

                    b.ToTable("nps_survey_responses", null, t =>
                        {
                            t.HasCheckConstraint("CK_nps_survey_responses_business_value", "business_value IS NULL OR business_value BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_nps_survey_responses_communication", "communication IS NULL OR communication BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_nps_survey_responses_quality", "quality IS NULL OR quality BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_nps_survey_responses_schedule", "schedule IS NULL OR schedule BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_nps_survey_responses_score", "score BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("PxOperations.Domain.ProjectHealth.ProjectHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionPlanComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_plan_comment");

                    b.Property<bool>("ActionPlanNeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("action_plan_needed");

                    b.Property<string>("ExpansionComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("expansion_comment");

                    b.Property<bool>("ExpansionOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("expansion_opportunity");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("highlights");

                    b.Property<int>("PracticesCount")
                        .HasColumnType("integer")
                        .HasColumnName("practices_count");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<string>("ReporterEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reporter_email");

                    b.Property<int>("Satisfaction")
                        .HasColumnType("integer")
                        .HasColumnName("satisfaction");

                    b.Property<int>("Schedule")
                        .HasColumnType("integer")
                        .HasColumnName("schedule");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SubProject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sub_project");

                    b.Property<DateOnly>("Week")
                        .HasColumnType("date")
                        .HasColumnName("week");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Week");

                    b.ToTable("project_health", (string)null);
                });

            modelBuilder.Entity("PxOperations.Domain.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client");

                    b.Property<int>("Dc")
                        .HasColumnType("integer")
                        .HasColumnName("dc");

                    b.Property<string>("DeliveryManager")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_manager");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Renewal")
                        .HasColumnType("integer")
                        .HasColumnName("renewal");

                    b.Property<string>("RenewalObservation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("renewal_observation");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("PxOperations.Domain.Milestones.Milestone", b =>
                {
                    b.HasOne("PxOperations.Domain.Projects.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.Contact", b =>
                {
                    b.HasOne("PxOperations.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.Dispatch", b =>
                {
                    b.HasOne("PxOperations.Domain.Nps.NpsCollection", null)
                        .WithMany("Dispatches")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.DispatchTarget", b =>
                {
                    b.HasOne("PxOperations.Domain.Nps.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PxOperations.Domain.Nps.Dispatch", null)
                        .WithMany("Targets")
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.NpsCollection", b =>
                {
                    b.HasOne("PxOperations.Domain.Projects.Project", null)
                        .WithOne()
                        .HasForeignKey("PxOperations.Domain.Nps.NpsCollection", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.SurveyResponse", b =>
                {
                    b.HasOne("PxOperations.Domain.Nps.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PxOperations.Domain.Nps.Dispatch", null)
                        .WithMany()
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PxOperations.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PxOperations.Domain.Nps.DispatchTarget", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PxOperations.Domain.ProjectHealth.ProjectHealth", b =>
                {
                    b.HasOne("PxOperations.Domain.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.Dispatch", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("PxOperations.Domain.Nps.NpsCollection", b =>
                {
                    b.Navigation("Dispatches");
                });

            modelBuilder.Entity("PxOperations.Domain.Projects.Project", b =>
                {
                    b.Navigation("Milestones");
                });
#pragma warning restore 612, 618
        }
    }
}
